name: Static Analysis

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python -m pip install flake8

      - name: Run flake8
        run: flake8 src | tee flake8_report.txt

      - name: Upload flake8 report if there are failures
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake8_report.txt

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pylint

      - name: Run pylint
        run: pylint --fail-under=7 src | tee pylint_report.txt

      - name: Upload pylint report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint_report.txt
